---
title: "DEEP: Future Fit"
author: "by Jess"
format:
    revealjs:
        theme: [solarized, custom.scss]
        slideNumber: true
        show-slide-number: all
        #reference-location: document
        #logo: images/logo.png
        footer: "https://deep-future-fit.netlify.app/"
        chalkboard:
            theme: whiteboard
        #code-annotations: hover
        css: styles.css
        mermaid:
          theme: default
        highlight-style: github
        #highlight-style: monochrome
        #logo: qr-code.png
        #multiplex: true
editor:
    render-on-save: true

---

# Review

# Gotta Go Fast

::: {.notes}
lossless but slow
:::

## Protocol Race

1. Get into groups of three and decide who will be the *client*, the *server*, and the *link*.

2. The client and server should stand on opposite sides of the field.

3. Server will have a buffer of X number of bytes and how many bytes it can remove from its buffer per turn. Only the server must know this.

## Protocol Race
When a round starts:

1. The client will write the number of bytes it wants to send to the server, and the link will deliver the message to the server.

2. The server will then do the following:
    - Remove bytes in the buffer
    - Check if there is space in the buffer for the incoming bytes, and if there is add them to the buffer and write a check mark on the whiteboard
    - If there is no space, write an X on the whiteboard.

## Protocol Race
3. The link will deliver the whiteboard back to the client. If the client receives an X, it can't send anything for 10 seconds. If the client receives a checkmark, it can move up however many steps it sent as bytes to the server.

The first client to reach the server wins.

# Discussion

# TCP

::: {.notes}
switch to ppt slides
:::

# Cybersecurity

## Mizi and Sua

Mizi wants to send a message to Sua, but...

TODO: include pictures

it's over the internet.

<br>

What should she do?

::: {.notes}
traditionally known as alice and bob

get a volunteer in the class and try to do this
:::

## Hashing

A hash function takes in a message (preimage) and returns a smaller message (hash value/digest)

A good hash function should be:

- Preimage resistant
- 2nd preimage resistant
- Collision resistant

Good default hash function as of June 2, 2026: [SHA256]{.highlight-red}

Avoid MD5!

## Ciphers
An algorithm that obfuscates information so that it seems random to anyone who does not possess "the key".

- Substitution ciphers
- One-Time pads

Symmetric encryption are ciphers that use a random key to encrypt and decrypt.

- Block ciphers
- Stream ciphers

Good default cipher as of June 2, 2026: [AES-256]{.highlight-red}

::: {.notes}
"the key", explain kerchkoff's principle
:::

## Asymmetric Encryption

- Every user has a public/private key pair
- The private and public keys reveal nothing about the other
- Messages encrypted with one key can only be decrypted with the other key

Encryption: the sender encrypts the message with the recipient’s public key.

Decryption: the recipient decrypts the message with their private key.

Good default cipher as of June 2, 2026: [RSA]{.highlight-red}


## Signatures

Proof that a message was sent by a particular person

- The sender signs the message with their private key
- The recipient verifies the signature with the sender's public key

## SSL

An SSL certificate contains a website's public key among other details.

- The format itself is called X.509

It is issued by a Certificate Authority (CA) whose certificate is installed in your computer.

It allows your browser to verify the identity of a website.

::: {.fragment .fade-in}
[You have to trust someone or something at some point.]{.highlight-red}
:::

::: {.notes}
can demo the certificate thing in browser

can also demo installed certificates
:::

# Q & A

# Graduation

# Showcase
